import os

from dotenv import load_dotenv

load_dotenv()

API_KEY = os.getenv("API_KEY")
COMPANY_ID = os.getenv("COMPANY_ID")
SANDBOX_API_KEY = os.getenv("SANDBOX_API_KEY")
SANDBOX_COMPANY_ID = os.getenv("SANDBOX_COMPANY_ID")
BLUECROSS_API_KEY = os.getenv("BLUECROSS_API_KEY")
BLUECROSS_COMPANY_ID = os.getenv("BLUECROSS_COMPANY_ID")
OTP_SECRET = os.getenv("OTP_SECRET")
UI_BASE_URL = os.getenv("UI_BASE_URL")
LOOKOUT_EMAIL = os.getenv("LOOKOUT_EMAIL")
LOOKOUT_PASSWORD = os.getenv("LOOKOUT_PASSWORD")
EMAIL_USER = os.getenv("EMAIL_USER")
EMAIL_PASSWORD = os.getenv("EMAIL_PASSWORD")
DEPUTY_BASE_URL = os.getenv("DEPUTY_BASE_URL")
DEPUTY_EMAIL = os.getenv("DEPUTY_EMAIL")
DEPUTY_PASSWORD = os.getenv("DEPUTY_PASSWORD")
AZURE_FORM_RECOGNIZER_ENDPOINT = os.getenv("AZURE_FORM_RECOGNIZER_ENDPOINT")
AZURE_FORM_RECOGNIZER_KEY = os.getenv("AZURE_FORM_RECOGNIZER_KEY")
